export const NOVA_TRANSACAO_REQUEST = 'NOVA_TRANSACAO_REQUEST';
export const NOVA_TRANSACAO_FAILURE = 'NOVA_TRANSACAO_FAILURE';
export const NOVA_TRANSACAO_SUCCESS = 'NOVA_TRANSACAO_SUCCESS';

export const NOVA_DESPESA_REQUEST = 'NOVA_DESPESA_REQUEST';
export const NOVA_DESPESA_FAILURE = 'NOVA_DESPESA_FAILURE';
export const NOVA_DESPESA_SUCCESS = 'NOVA_DESPESA_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_FAILURE = 'EDIT_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const MODO_NOTURNO_SUCCESS = 'MODO_NOTURNO_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
