export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const NOVA_TRANSACAO_REQUEST = 'NOVA_TRANSACAO_REQUEST';
export const NOVA_TRANSACAO_FAILURE = 'NOVA_TRANSACAO_FAILURE';
export const NOVA_TRANSACAO_SUCCESS = 'NOVA_TRANSACAO_SUCCESS';

export const NOVA_DESPESA_REQUEST = 'NOVA_DESPESA_REQUEST';
export const NOVA_DESPESA_FAILURE = 'NOVA_DESPESA_FAILURE';
export const NOVA_DESPESA_SUCCESS = 'NOVA_DESPESA_SUCCESS';

export const PAGAR_DESPESA_REQUEST = 'PAGAR_DESPESA_REQUEST';
export const PAGAR_DESPESA_FAILURE = 'PAGAR_DESPESA_FAILURE';

export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_FAILURE = 'EDIT_FAILURE';

export const NOVAMETA_REQUEST = 'NOVAMETA_REQUEST';
export const NOVAMETA_FAILURE = 'NOVAMETA_FAILURE';

export const VERMETAS_REQUEST = 'VERMETAS_REQUEST';
export const VERMETAS_FAILURE = 'VERMETAS_FAILURE';

export const DEPOSITARMETAS_REQUEST = 'DEPOSITARMETAS_REQUEST';
export const DEPOSITARMETAS_FAILURE = 'DEPOSITARMETAS_FAILURE';

export const VERDETALHESMETAS_REQUEST = 'VERDETALHESMETAS_REQUEST';
export const VERDETALHESMETAS_FAILURE = 'VERDETALHESMETAS_FAILURE';

export const NOVO_PLANEJAMENTO_MENSAL_REQUEST = 'NOVO_PLANEJAMENTO_MENSAL_REQUEST';
export const NOVO_PLANEJAMENTO_MENSAL_FAILURE = 'NOVO_PLANEJAMENTO_MENSAL_FAILURE';

export const NOVO_CARTAO_REQUEST = 'NOVO_CARTAO_REQUEST';
export const NOVO_CARTAO_FAILURE = 'NOVO_CARTAO_FAILURE';
export const NOVO_CARTAO_SUCCESS = 'NOVO_CARTAO_SUCCESS';

export const EDIT_CONFIG_REQUEST = 'EDIT_CONFIG_REQUEST';
export const EDIT_CONFIG_FAILURE = 'EDIT_CONFIG_FAILURE';
export const EDIT_CONFIG_SUCCESS = 'EDIT_CONFIG_SUCCESS';

export const MODO_NOTURNO_SUCCESS = 'MODO_NOTURNO_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
